apiVersion: v1
kind: Pod
metadata:
  name: conv-app
  labels:
    component: front
spec:
  containers:
    - name: conv-app
      image: antonlarichev/conv-app:1.2
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: '1556Mi'
          cpu: '1'
          ephemeral-storage: '3000Mi'